
export const metadata = {
  title: 'GOOD GOOD | planning app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  
      <section>
        {children}
      </section>

  );
}
